# Generated by Django 4.2.14 on 2024-07-19 11:39

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Аутентификация по лицу', 'Face Id'), ('Запись видео', 'Rec'), ('Обычная камера', 'Default')], max_length=50)),
                ('created', models.DateTimeField(default=core.models.default_now)),
                ('updated', models.DateTimeField(default=core.models.default_now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=core.models.default_now)),
                ('updated', models.DateTimeField(default=core.models.default_now)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('На хранении', 'In Storage'), ('Уничтожен', 'Destroyed'), ('Взят', 'Taken'), ('На экспертизе', 'On Examination'), ('В архиве', 'Archived')], default='На хранении', max_length=50)),
                ('barcode', models.CharField(default=core.models.create_barcode_value, max_length=255)),
                ('created', models.DateTimeField(default=core.models.default_now)),
                ('updated', models.DateTimeField(default=core.models.default_now)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_evidences', to='core.case')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=core.models.default_now)),
                ('updated', models.DateTimeField(default=core.models.default_now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.DateTimeField(default=core.models.default_now)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEvidenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('На хранении', 'In Storage'), ('Уничтожен', 'Destroyed'), ('Взят', 'Taken'), ('На экспертизе', 'On Examination'), ('В архиве', 'Archived')], max_length=50)),
                ('created', models.DateTimeField(default=core.models.default_now)),
                ('material_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.materialevidence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='materialevidence',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='FaceID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created', models.DateTimeField(default=core.models.default_now)),
                ('updated', models.DateTimeField(default=core.models.default_now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.user'),
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('fields', models.TextField()),
                ('data', models.TextField()),
                ('created', models.DateTimeField(default=core.models.default_now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
        ),
    ]
