# Generated by Django 4.2.14 on 2024-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
